version: 2
updates:
  # CLI dependency updates
  - package-ecosystem: gomod
    directory: /cli
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: release/v1.4.x
    reviewers:
      - compose-generator/compiler-team
    assignees:
      - marcauberer

  # Java compiler dependency updates
  - package-ecosystem: maven
    directory: /compiler/java
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: release/v1.4.x
    reviewers:
      - compose-generator/compiler-team
    assignees:
      - marcauberer

  # Main Dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: release/v1.4.x
    reviewers:
      - compose-generator/compiler-team
    assignees:
      - marcauberer
      
  # Github Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: release/v1.4.x
    reviewers:
      - compose-generator/compiler-team
    assignees:
      - marcauberer
