project_name: ccom
builds:
  - dir: cli
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 5
      - 6
      - 7
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }} -X main.builtBy=github-actions
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - bin/ccomc-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}/* # Waiting for implementation: https://github.com/goreleaser/goreleaser/issues/1638
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
nfpms:
  - id: publish
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    maintainer: Marc Auberer <marc.auberer@chillibits.com>
    description: Compiler for the CCom (Conditional Comments) language.
    homepage: https://github.com/compose-generator/ccom
    license: MIT
    bindir: /usr/bin
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: bin/ccomc-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}/*
        dst: /usr/lib/ccom/
dockers:
  - image_templates:
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/compose-generator/ccom:{{ .Major }}-amd64
      - ghcr.io/compose-generator/ccom:latest-amd64
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}-amd64
      - chillibits/ccom:{{ .Major }}-amd64
      - chillibits/ccom:latest-amd64
    dockerfile: Dockerfile
    use: buildx
    goarch: amd64
    extra_files:
      - bin
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --build-arg=COMPILER_PATH=linux-amd64
      - --platform=linux/amd64
  - image_templates:
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}-i386
      - ghcr.io/compose-generator/ccom:{{ .Major }}-i386
      - ghcr.io/compose-generator/ccom:latest-i386
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}-i386
      - chillibits/ccom:{{ .Major }}-i386
      - chillibits/ccom:latest-i386
    dockerfile: Dockerfile
    use: buildx
    goarch: 386
    extra_files:
      - bin
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --build-arg=COMPILER_PATH=linux-386
      - --platform=linux/i386
  - image_templates:
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}-arm32v7
      - ghcr.io/compose-generator/ccom:{{ .Major }}-arm32v7
      - ghcr.io/compose-generator/ccom:latest-arm32v7
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}-arm32v7
      - chillibits/ccom:{{ .Major }}-arm32v7
      - chillibits/ccom:latest-arm32v7
    dockerfile: Dockerfile
    use: buildx
    goarch: arm
    goarm: 7
    extra_files:
      - bin
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --build-arg=COMPILER_PATH=linux-armv7
      - --platform=linux/arm/v7
  - image_templates:
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}-arm64v8
      - ghcr.io/compose-generator/ccom:{{ .Major }}-arm64v8
      - ghcr.io/compose-generator/ccom:latest-arm64v8
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}-arm64v8
      - chillibits/ccom:{{ .Major }}-arm64v8
      - chillibits/ccom:latest-arm64v8
    dockerfile: Dockerfile
    use: buildx
    goarch: arm64
    extra_files:
      - bin
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --build-arg=COMPILER_PATH=linux-arm64
      - --platform=linux/arm64/v8
docker_manifests:
  - name_template: chillibits/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8
    skip_push: auto
  - name_template: chillibits/ccom:{{ .Major }}.{{ .Minor }}
    image_templates:
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}-amd64
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}-i386
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}-arm32v7
      - chillibits/ccom:{{ .Major }}.{{ .Minor }}-arm64v8
    skip_push: auto
  - name_template: chillibits/ccom:{{ .Major }}
    image_templates:
      - chillibits/ccom:{{ .Major }}-amd64
      - chillibits/ccom:{{ .Major }}-i386
      - chillibits/ccom:{{ .Major }}-arm32v7
      - chillibits/ccom:{{ .Major }}-arm64v8
    skip_push: auto
  - name_template: chillibits/ccom:latest
    image_templates:
      - chillibits/ccom:latest-amd64
      - chillibits/ccom:latest-i386
      - chillibits/ccom:latest-arm32v7
      - chillibits/ccom:latest-arm64v8
    skip_push: auto

  - name_template: ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8
    skip_push: auto
  - name_template: ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}-i386
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}-arm32v7
      - ghcr.io/compose-generator/ccom:{{ .Major }}.{{ .Minor }}-arm64v8
    skip_push: auto
  - name_template: ghcr.io/compose-generator/ccom:{{ .Major }}
    image_templates:
      - ghcr.io/compose-generator/ccom:{{ .Major }}-amd64
      - ghcr.io/compose-generator/ccom:{{ .Major }}-i386
      - ghcr.io/compose-generator/ccom:{{ .Major }}-arm32v7
      - ghcr.io/compose-generator/ccom:{{ .Major }}-arm64v8
    skip_push: auto
  - name_template: ghcr.io/compose-generator/ccom:latest
    image_templates:
      - ghcr.io/compose-generator/ccom:latest-amd64
      - ghcr.io/compose-generator/ccom:latest-i386
      - ghcr.io/compose-generator/ccom:latest-arm32v7
      - ghcr.io/compose-generator/ccom:latest-arm64v8
    skip_push: auto
release:
  name_template: v{{ .Tag }}
  prerelease: auto
  footer: |
    ## What to do next?
    - [Install CCom](https://ccom.compose-generator.com/install/linux/)
    - Visit [ccom.compose-generator.com](https://ccom.compose-generator.com) to test the new features
    - Follow [@composegen](https://twitter.com/composegen) on Twitter
changelog:
  use: github
  filters:
    exclude:
    - Merge pull request
    - Merge branch
milestones:
  - close: true
    fail_on_error: false