site_name: CCom
site_url: https://ccom.compose-generator.com
site_description: Compiler for the CCom (Conditional Comments) language
site_author: Marc Auberer
copyright: Made with ❤️ by Compose Generator contributors, powered by <a href="https://www.chillibits.com" target="_blank">ChilliBits</a>.
repo_name: compose-generator/ccom
repo_url: https://github.com/compose-generator/ccom
edit_uri: edit/main/docs/docs/

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  logo: static/avatar.png
  favicon: static/favicon-48x48.ico
  include_search_page: false
  search_index_only: true
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - stylesheets/styles.css

plugins:
  - search:
      prebuild_index: python
      lang:
      - en
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/compose-generator/ccom
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/composegen
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/chillibits/ccom

nav:
  - Home: index.md
  - intro.md
  - Install:
    - install/docker.md
    - install/linux.md
    - install/windows.md
    - install/source.md
  - usage.md
  - contributing.md

markdown_extensions:
  - codehilite
  - meta
  - footnotes
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg