# C++ CI workflow
name: C++ CI

on:
  push:
    paths:
      - compiler/cpp/**
  pull_request:
    branches: [ main, release/**, feature/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          shopt -s extglob
          rm -rf !("compiler")
          cp -fR ./compiler/cpp/* .
          rm -rf ./compiler

      - name: Download Libs
        run: |
          mkdir -p ./lib/json
          cd lib
          git clone --depth 1 --branch v1.15.2 https://github.com/google/googletest.git
          curl -sSL "https://github.com/nlohmann/json/releases/download/v3.11.3/json.hpp" --output json/json.hpp

      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4
        with:
          submodule_update: ON
          run_tests: ON
          cmake_args: -DWITH_TESTS=ON
          unit_test_build: -Dtest=ON