name: C++ CI

on:
  push:
    paths:
      - 'compiler/c++/**'
  pull_request:
    branches: [ main, dev, feature/** ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare environment
      run: |
        shopt -s extglob
        rm -rf !("compiler/c++")
        cp -fR ./compiler/c++/* .
        rm -rf ./compiler/c++
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        submodule_update: ON
        run_tests: ON
        unit_test_build: -Dtest=ON