name: C++ CI

on:
  push:
    paths:
      - 'compiler/**'
  pull_request:
    branches: [ main, dev, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./compiler
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        submodule_update: ON
        run_tests: ON
        unit_test_build: -Dtest=ON