# Go CI

name: Go CI

on:
  push:
    paths:
      - 'cli/**'
  pull_request:
    branches: [ main, dev, feature/** ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare environment
        working-directory: cli
        run: |
          go get -u golang.org/x/lint/golint
          go mod vendor

      - name: Run vet & lint
        working-directory: cli
        run: |
          go vet ./...
          golint ./...

      - name: Run build
        working-directory: cli
        run: go build -x
          
      - name: Run tests
        working-directory: cli
        run: go test ./...

      - name: Install GoSec
        shell: bash
        run: curl -sfL https://raw.githubusercontent.com/securego/gosec/v2.8.1/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.8.1

      - name: Run security scan
        working-directory: cli
        run: gosec -exclude=G204 ./...