# Go CI

name: Go CI

on:
  push:
    paths:
      - 'cli/**'
  pull_request:
    branches: [ main, dev, feature/** ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Run build
        run: go build -x

      - name: Run vet & lint
        run: |
          go vet .
          golint .
          
      - name: Run tests
        run: go test