# Workflow to detect typos in docs and source code
name: Misspell

on:
  push:
    branches:
      - main
      - release/**
      - docs/**
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          exclude: ./cli/vendor/**
          locale: US